name: dl_verano19
channels:
- anaconda
- pytorch
- defaults
- conda-forge
dependencies:
- scipy
- cuda90
- cudnn
- numpy
- pillow
- jpeg
- zlib
- freetype
- libtiff
- bleach
- certifi
- cffi
- cycler
- decorator
- entrypoints
- expat
- html5lib
- icu
- ipykernel
- ipython
- ipython_genutils
- ipywidgets
- jedi
- jinja2
- jsonschema
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- jupyter_contrib_nbextensions
- libiconv
- libpng
- libsodium
- libxml2
- markupsafe
- matplotlib
- nbformat
- notebook
- olefile
- openssl
- pandas
- patsy
- pcre
- pexpect
- pickleshare
- pip
- prompt_toolkit
- pycparser
- pygments
- pyparsing
- pyqt
- python>=3.6.0
- python-dateutil
- pytz
- pyzmq
- qt
- qtconsole
- scipy
- seaborn
- setuptools
- simplegeneric
- sip
- six
- sqlite
- statsmodels
- testfixtures
- tk
- tqdm
- traitlets
- wcwidth
- wheel
- widgetsnbextension
- xz
- zeromq
- pytorch
- cython
